version: '3'

services:

  simple_blog:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
